snapdealapp/urls.py
from django.urls import path
from django.conf.urls import url
from snapdealapp.views import *
app_name="snapdealapp"

urlpatterns = [
    url(r'^$',CategoryMainPage.as_view(),name="main_html"),
    path('signup/', signup, name='signup'),
    path('login/',LoginController.as_view(),name="login_html"),
    path('logout/',logout_user,name="logout_html"),

    path("category/",CategoryListView.as_view(),name="category_html"),
    path("category/add",CreateCategoryView.as_view(),name="categoryadd_html"),
    path('category/<int:pk>/edit',UpdateCategoryView.as_view(),name="edit_category_html"),
    path('category/<int:pk>/delete',DeleteCategoryView.as_view(),name="delete_category_html"),


    path("category/<int:pk>", ProductList.as_view(), name="product_html"),
    path("category/<int:pk>/product/add", CreateProductView.as_view(), name="product_add_html"),
    path("product/<int:pk>",ProductDetails.as_view(),name='product_details_html'),
    path("category/<int:category_id>/product/<int:pk>/edit",UpdateProductView.as_view(),name="product_edit_html"),
    path("category/<int:category_id>/product/<int:pk>/delete",DeleteProductView.as_view(),name="product_delete_html"),

    path("category/<int:pk>/add_to_cart",add_to_cart,name="add_to_cart"),
    path("cart/<int:pk>/delete",DeleteCartView.as_view(),name="remove_from_cart"),
    path("cart",Cartlistview.as_view(),name='cart'),

    path("cart/clear",clear_cart,name='clear_cart'),
    path("placeorder/", place_order, name="place_order"),
    path("order", Orderlistview.as_view(), name="order_html"),
    path("order/", order, name="order"),
    path("orderedlist/<int:pk>/delete", DeleteOrderedlistView.as_view(), name="remove_from_orderedlist"),

    path('search/', search_all, name='list'),

    path('categorysearch/<slug:string>/', SearchCategoryView, name='list_category'),
    path('productsearch/<slug:string>/', SearchProductView, name='list_product'),

    path("address", AddressListView.as_view(), name="address_html"),
    path("address/<int:pk>/delete", DeleteAddressView.as_view(), name="address_delete_html"),
    path("address/<int:pk>/edit", UpdateAddressView.as_view(), name="address_edit_html"),
    path("address/add", CreateAddressView.as_view(), name="address_add_html"),

    path('payment_success',payment_success,name='payment_success'),
    path('payment_options',payment_options,name='payment_options'),
    path('allproducts',AllProducts.as_view(),name='allproducts'),

]

snapdealproject/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('snapdealapp.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

snapdealapp/views.py
from django.shortcuts import render

# Create your views here.

snapdealapp/views/address.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from  snapdealapp.models import Address

from django.views.generic import DetailView, CreateView, UpdateView, DeleteView, ListView
from django import forms
from django.shortcuts import *
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
class AddressListView(LoginRequiredMixin,ListView):
    login_url = '/login/'
    model =Address
    context_object_name = 'address'
    template_name = "address.html"

    def get_context_data(self, **kwargs):
        context = super(AddressListView, self).get_context_data(**kwargs)
        user = self.request.user

        print(type(user))
        address = list(
            Address.objects.values('id', 'country', 'fullname','mobileno','pincode','city','street',
             'landmark','state' ,'address_type').filter(user_id=user.id))

        context.update({
            'user_permissions': self.request.user.get_all_permissions(),
            'address': address,
        })
        return context

class AddressForm(forms.ModelForm):
    mobileno = forms.RegexField(regex=r'^\+?1?\d{9,15}$',
                                widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'mobileno'}),
                                help_text=(
                                    "Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")),

    class Meta:
        model = Address
        exclude= ['id','user']

        # fields = ('country', 'fullname', 'pincode','street','mobileno','landmark','city','state','address_type' , )
        widgets={
            'country':forms.TextInput(attrs={'class':'form-control' ,'placeholder':'enter title'  }),
            'fullname': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter title'}),
            'mobileno':forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter title'}),
            'pincode': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter title'}),
            'street': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter title'}),
            'landmark': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter title'}),
            'city': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter title'}),
            'state': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter title'}),
            'address_type': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter title'}),
        }
from django.views.generic.edit import CreateView
class CreateAddressView(LoginRequiredMixin,CreateView):
    login_url = '/login/'
    model = Address
    form_class = AddressForm
    template_name = 'addressForm.html'

    def get_context_data(self, **kwargs):
        context = super(CreateAddressView, self).get_context_data(**kwargs)
        context.update({'address_form': context.get('form')})
        return context
    def post(self, request, *args, **kwargs):
        address_form = AddressForm(request.POST)
        if address_form.is_valid():
            address = address_form.save(commit=False)
            address.user = request.user
            address.save()
        return redirect('snapdealapp:address_html')

class UpdateAddressView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    model = Address
    form_class = AddressForm
    template_name = 'addressForm.html'

    def get_context_data(self, **kwargs):
        context = super(UpdateAddressView, self).get_context_data(**kwargs)
        address_form = context.get('address')
        context.update({'address_form': context.get('form')})
        return context

    def post(self, request, *args, **kwargs):
        address = Address.objects.get(pk=kwargs.get('pk'))
        form = AddressForm(request.POST, request.FILES, instance=address)
        form.save()
        return redirect('snapdealapp:address_html')



class DeleteAddressView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Address
    template_name = 'deleteform.html'
    success_url = reverse_lazy('snapdealapp:cart')

    def has_permission(self):
        user_id = self.request.user.id
        check_user = Address.objects.get(pk=self.kwargs['pk']).user.id

        if not user_id == check_user:
            self.raise_exception = True
            success_url = reverse_lazy('snapdealapp:address_html')
            return False
        else:
            def get(self, request, *args, **kwargs):
                return self.post(request, args, kwargs)

            success_url = reverse_lazy('snapdealapp:address_html')
            return True

snapdealapp/views/cart.py
from  snapdealapp.models import *

from django.views.generic import DeleteView, ListView

from django.shortcuts import *
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

class Cartlistview(LoginRequiredMixin, ListView):
    login_url = '/login/'
    model = Cart
    context_object_name = 'cart'
    template_name = "cart.html"

    def get_queryset(self):
        user = self.request.user
        return Cart.objects.filter(user=user)

    def get_context_data(self, **kwargs):
        context = super(Cartlistview, self).get_context_data(**kwargs)
        context.update({'user_permissions': self.request.user.get_all_permissions()})
        return context



def add_to_cart(request,**kwargs):

    if request.user.is_authenticated:

        product_id = kwargs.get('pk')
        user = request.user
        product = Product.objects.get(id=product_id)
        try:
            cart=Cart.objects.get(user=user)
            if product in list(cart):
                pass
            else:
                itemtocart = Cart(user=user, products=product, subtotal=product.price, image=product.image, quantity=1)
                itemtocart.save()
                return redirect('snapdealapp:cart')

            return redirect('snapdealapp:cart')
        except:

            itemtocart = Cart(user=user, products=product, subtotal=product.price, image=product.image,quantity=1)
            itemtocart.save()
            return redirect('snapdealapp:cart')
    else:
        return redirect('snapdealapp:login_html')



class DeleteCartView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):

    model = Cart
    template_name = 'deleteform.html'
    success_url = reverse_lazy('snapdealapp:cart')

    def has_permission(self):
        user_id = self.request.user.id
        check_user = Cart.objects.get(pk=self.kwargs['pk']).user.id


        if not user_id == check_user:
            self.raise_exception = True
            success_url = reverse_lazy('snapdealapp:cart')
            return False
        else:
            def get(self, request, *args, **kwargs):
                return self.post(request, args, kwargs)

            success_url = reverse_lazy('snapdealapp:cart')
            return True



def clear_cart(request):
    price = 0
    import ipdb
    ipdb.set_trace()
    try:
        c = list(Cart.objects.values().filter(user_id=request.user.id))
        for i in c:
            product_id = i['products_id']
            product = Product.objects.get(id=product_id)
            price += product.price
            car = Cart.objects.get(id=i['id'])
            car.delete()

        return redirect('snapdealapp:cart')

    except:
        return redirect('snapdealapp:cart')

snapdealapp/views/category.py
from django.views.generic import ListView, DetailView ,CreateView, UpdateView , DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import *

from snapdealapp.models import *


class CategoryMainPage(ListView):
    login_url = '/login/'

    model = Category
    context_object_name='category'
    template_name = "category_main.html"

    def get_context_data(self,**kwargs):
        context=super(CategoryMainPage,self).get_context_data(**kwargs)
        product = list(
            Category.objects.values('id', 'product__id', 'product__title', 'product__image', 'product__description',
                                    'product__price', 'product__rating'))
        for i in product:
            if i['product__id'] is None:
                product = None

        context.update({
            'user_permissions': self.request.user.get_all_permissions(),
            'product': product,
        })
        return context


class AllProducts(ListView):
    login_url = '/login/'

    model = Product
    context_object_name='product'
    template_name = "productSearchResults.html"

    def get_context_data(self,**kwargs):
        context=super(AllProducts,self).get_context_data(**kwargs)
        return context
class CategoryListView(ListView):
    login_url = '/login/'

    model = Category
    context_object_name='category'
    template_name = "category.html"

    def get_context_data(self,**kwargs):
        context=super(CategoryListView,self).get_context_data(**kwargs)
        # import ipdb
        # ipdb.set_trace()
        # pass
        return context



class ProductList(ListView):
    login_url = '/login/'

    model = Product
    context_object_name = 'category'
    template_name = "category.html"

    def get_context_data(self, **kwargs):
        context = super(ProductList, self).get_context_data(**kwargs)
        # import ipdb
        # ipdb.set_trace()
        # pass
        return context


from django import forms
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        exclude= ['id','active']
        widgets={
            'title':forms.TextInput(attrs={'class':'form-control' ,'placeholder':'enter title'  }),
            'description': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter description'}),
        }

from django.views.generic.edit import CreateView
class CreateCategoryView(CreateView):

    model=Category
    form_class = CategoryForm
    template_name = 'categoryForm.html'

    success_url=reverse_lazy('snapdealapp:category_html')




class UpdateCategoryView(UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = 'categoryForm.html'
    success_url = reverse_lazy('snapdealapp:category_html')


class DeleteCategoryView(DeleteView):
    model=Category
    success_url = reverse_lazy('snapdealapp:category_html')
    def get(self,request,*args,**kwargs):
        return self.post(request,args,kwargs)

snapdealapp/views/order.py
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy

from django.views.generic import ListView, DetailView,DeleteView
from django.contrib.auth.mixins import *
from snapdealapp.models import *
class Orderlistview(LoginRequiredMixin, ListView):
    login_url = '/login/'
    model = OrderedItems
    context_object_name = 'order'
    template_name = "order.html"
    def get_queryset(self):
        user = self.request.user
        return OrderedItems.objects.filter(user=user)

    def get_context_data(self, **kwargs):
        c = list(OrderedItems.objects.values().filter(user_id=self.request.user.id))

        price=0
        for i in c:
            product_id = i['products_id']
            product = Product.objects.get(id=product_id)
            price += product.price

        context = super(Orderlistview, self).get_context_data(**kwargs)
        context.update({'user_permissions': self.request.user.get_all_permissions()})
        context.update({'total': price})

        return context


@login_required
def order(request,**kwargs):
    return redirect('snapdealapp:order_html')

@login_required
def place_order(request,**kwargs):

    price=0
    try:
        c=list(Cart.objects.values().filter(user_id=request.user.id))
        for i in c:
            product_id = i['products_id']
            product = Product.objects.get(id=product_id)
            price+=product.price
            order= OrderedItems(user=request.user, products=product, subtotal=product.price, image=product.image, quantity=1)
            order.save()
            car = Cart.objects.get(id=i['id'])
            car.delete()

        return redirect('snapdealapp:order_html')

    except:
        pass
        return redirect('snapdealapp:order_html')

class DeleteOrderedlistView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = OrderedItems
    template_name = 'deleteform.html'
    success_url = reverse_lazy('snapdealapp:order_html')

    def has_permission(self):
        user_id = self.request.user.id
        check_user =OrderedItems.objects.get(pk=self.kwargs['pk']).user.id

        if not user_id == check_user:
            self.raise_exception = True
            success_url = reverse_lazy('snapdealapp:order_html')
            return False
        else:
            def get(self, request, *args, **kwargs):
                return self.post(request, args, kwargs)

            success_url = reverse_lazy('snapdealapp:order_html')
            return True

snapdealapp/views/payment.py
from django import forms
from django.shortcuts import render
def payment_success(request):
    return render(request, 'payment_success.html')

class ProductForm(forms.ModelForm):
    class Meta:


        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter title'}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter price'}),
            'units': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter units'}),
            'rating': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter rating'}),
            'description': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter description'}),
        }
def payment_options(request):
    return render(request, 'payment_options.html')

snapdealapp/templates/cart.html
{% extends "project.html" %}
{% load staticfiles  %}
{% block content %}
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
<script defer src="https://code.getmdl.io/1.3.0/material.min.js">
</script><style>
    a {
        text-decoration: none !important;
    }
    .material-icons {
        display: inline-flex;
        vertical-align: middle;
    }
    .mdl-card__title{
        align:center !important;
    }


</style>
{%if cart%}
<a href="{% url 'snapdealapp:clear_cart'%}" class="btn btn-info btn-md">clear_cart</a>
<a href="{% url 'snapdealapp:address_html' %}" class="btn btn-info btn-md">checkout</a>

 {% for items in cart%}
<div align="left">
    <div class="mdl-grid">
        <div class="mdl-cell mdl-cell--8-col">
            <div class="mdl-card mdl-shadow--2dp" style="width: 100%">

                <div class="mdl-grid" style="margin: 0;">
                    <div class="mdl-cell mdl-cell--6-col">
                        <div class="mdl-card__supporting-text">
                            <img src="/media/{{items.products.image}}" width="280px" height="280px" style=""/>
                        </div>
                    </div>
                    <div class="mdl-cell mdl-cell--6-col">
                        <p>
                            {{items.products.title}}
                        </p>
                        <p>
                            <b>INFO:</b> {{items.products.description}}
                        </p>
                        <p>
                            <b>
                                Price:</b> {{items.products.price}}
                        </p>
                              <a class="btn btn-primary btn-lg active" href="{% url 'snapdealapp:product_details_html' items.products.id%}">view_product</a>
                        </p>
                        <p>
        <a  class="btn btn-primary btn-lg active" href="{% url 'snapdealapp:remove_from_orderedlist' items.id%}">remove_product</a>
                        </p>
                        <!-- Colored raised button -->

                    </div>
                </div>

            </div>

        </div>
    </div>
</div>
   {% endfor %}
	{% else %}
	   <CENTER><H4>Your cart is empty!!</H4>
 <a class="btn btn-primary"  href="{% url 'snapdealapp:main_html'%}" >
   SHOP HERE
  </a></CENTER>
	{% endif %}

{% endblock %}

snapdealapp/templates/category_main.html
{% extends "project.html" %}
{% load staticfiles  %}
{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.2/owl.carousel.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.2/owl.carousel.js"></script>

<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
<script defer src="https://code.getmdl.io/1.3.0/material.min.js">
</script>
<script>
    $(document).ready(function() {

  $("#owl-demo").owlCarousel({

    autoPlay: 3000, //Set AutoPlay to 3 seconds

    items: 4,
    itemsDesktop: [1199, 3],
    itemsDesktopSmall: [979, 3]

  });
});
</script>
<style>
    a {
        text-decoration: none !important;
    }
    .material-icons {
        display: inline-flex;
        vertical-align: middle;
    }
    .mdl-card__title{
        align:center !important;
    }


</style>
<div class="container">

  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
	  <li data-target="#myCarousel" data-slide-to="3"></li>
      <li data-target="#myCarousel" data-slide-to="4"></li>
	  <li data-target="#myCarousel" data-slide-to="5"></li>
      <li data-target="#myCarousel" data-slide-to="6"></li>
	  <li data-target="#myCarousel" data-slide-to="7"></li>
      <li data-target="#myCarousel" data-slide-to="8"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">

      <div class="item active">
        <img src="{% static  'x1.jpg' %}" alt="Los Angeles" style="width:100%;">
        <div class="carousel-caption">
          <h3>T-shirts</h3>
          <p>The hot sale:)</p>
        </div>
      </div>
     <div class="item">
            <img src="{% static  's1.jpg' %}"alt="Chicago" style="width:100%;">

      </div>
      <div class="item">
        <img src="{% static  'p2.jpg' %}"alt="Chicago" style="width:100%;">
        <div class="carousel-caption">
          <h3>Furniture and matress</h3>
          <p>Be furnisure!!</p>
        </div>
      </div>
          <div class="item">
        <img src="{% static  'bb.jpg' %}"alt="Chicago" style="width:100%;">

      </div>
         <div class="item">
        <img src="{% static  'k1.jpg' %}"alt="Chicago" style="width:100%;">
        <div class="carousel-caption">

        </div>
      </div>

         <div class="item">
        <img src="{% static  'x2.jpg' %}"alt="Chicago" style="width:100%;">
        <div class="carousel-caption">
          <h3>Alo Jel</h3>
          <p>nature's product!</p>
        </div>
      </div>
         <div class="item">
        <img src="{% static  'x3.jpg' %}"alt="Chicago" style="width:100%;">
        <div class="carousel-caption">

        </div>
      </div>



    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<div style=”float:right”>
    {% if request.user.is_superuser %}
    <a class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect" href="{{categoryID}}/product/add">
               + Add Product
        </a>
		 {% endif %}
        <br>
</div>


<div class="mdl-grid">


{% if product%}
    {% for obj in product %}

    <div class="mdl-cell mdl-cell--3-col">
        <div class="mdl-card mdl-shadow--4dp" style="width:240px;text-align:center;">

            <a href="{% url 'snapdealapp:product_details_html' obj.product__id %}">
                <img src="/media/{{obj.product__image}}" height="130px" width="130px" style="margin: auto; padding-top:12px;"/>
            </a>


             <div class="mdl-card__supporting-text">
                 <p>{{obj.product__title}}</p>


             </div>
 {% if request.user.is_superuser %}
            <div class="mdl-card__actions mdl-card--border">

				<a href="{% url 'snapdealapp:product_edit_html' obj.id obj.product__id %}">edit</a>
				<a href="{% url 'snapdealapp:product_delete_html' obj.id obj.product__id %}">delete</a>
        {% endif %}

     </div>
    </div>

    </div>
    {%endfor%}
       {% endif %}
</div>


{% endblock %}

snapdealapp/templates/product.html
{% extends "project.html" %}
{% load staticfiles  %}
{% block content %}
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
<script defer src="https://code.getmdl.io/1.3.0/material.min.js">
</script><style>
    a {
        text-decoration: none !important;
    }
    .material-icons {
        display: inline-flex;
        vertical-align: middle;
    }
    .mdl-card__title{
        align:center !important;
    }


</style>
<div style=”float:right”>
    {% if request.user.is_superuser %}
    <a class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect" href="{{categoryID}}/product/add">
               + Add Product
        </a>
		 {% endif %}
        <br>
</div>

<div class="mdl-grid">


{% if product%}
    {% for obj in product %}

    <div class="mdl-cell mdl-cell--3-col">
        <div class="mdl-card mdl-shadow--4dp" style="width:240px;text-align:center;">

            <a href="{% url 'snapdealapp:product_details_html' obj.product__id %}">
                <img src="/media/{{obj.product__image}}" height="190px" width="200px" style="margin: auto; padding-top:12px;"/>
            </a>


             <div class="mdl-card__supporting-text">
                <strong style="color:black">{{obj.product__title}}</strong>
                 <br> <strong style="color:black">price:{{obj.product__price}}</strong>
             </div>
 {% if request.user.is_superuser %}
            <div class="mdl-card__actions mdl-card--border">

				<a href="{% url 'snapdealapp:product_edit_html' obj.id obj.product__id %}">edit</a>
				<a href="{% url 'snapdealapp:product_delete_html' obj.id obj.product__id %}">delete</a>
        {% endif %}

     </div>
    </div>

    </div>
    {%endfor%}
       {% endif %}
</div>
<br>
{% endblock %}

snapdealapp/templates/searchcategory.html
{% extends "project.html" %}
{% load staticfiles  %}
{% block content %}

	<div class="container">
		 <h1 align="center">Your search results</h1>
		 <br>
		 <br>
        {% if request.user.is_superuser %}
			 <button class="btn btn-default active"><a href="{% url 'snapdealapp:categoryadd_html' %}">Add Category</a></button>
		 {% endif %}
		 <br>
		 <br>
	{% if category %}
	<div class="container">
		<div class="row">
	    {% for cat in category %}
			<div class="col-md-4 responsive" id={item.id}>
			<a href="{% url 'snapdealapp:product_html' cat.id %}" >
                      <div class="thumbnail">

                          <div  class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                <div class="item active">
                                {% if cat.image %}
										<img src="{{ cat.image.url }}" class="img-responsive img-rounded"  height="400px" width="300px" >
							{% endif %}
                            <div class="carousel-caption">
                                          <h2>{{ cat.title }}</h2>
                                      <p>{{cat.description}}</p>
                                   </div>
                                </div>
                            </div>
                        </div>


					  </div>
			</a>
            {% if request.user.is_superuser %}
                <a href="{% url 'snapdealapp:edit_category_html' cat.id %}" >edit</a>


	            <a href="{% url 'snapdealapp:delete_category_html' cat.id %}" >delete</a>
                {% endif %}
			</div>

	    {% endfor %}

		</div>
	</div>
	{% else %}
	    <p>No categories to show</p>
	{% endif %}
	</div>
{% endblock %}

snapdealapp/templates/searchcategoryfail.html
{% extends "project.html" %}
{% load staticfiles  %}
{% block content %}

	<div class="container">
		 <h1 align="center">No such category available but you can find similar products here</h1>
		 <br>
		 <br>
        {% if request.user.is_superuser %}
			 <button class="btn btn-default active"><a href="{% url 'snapdealapp:categoryadd_html' %}">Add Category</a></button>
		 {% endif %}
		 <br>
		 <br>
	{% if category %}
	<div class="container">
		<div class="row">
	    {% for cat in category %}
			<div class="col-md-4 responsive" id={item.id}>
			<a href="{% url 'snapdealapp:product_html' cat.id %}" >
                      <div class="thumbnail">

                          <div  class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                <div class="item active">
                                {% if cat.image %}
								<img src="{{ cat.image.url }}" class="img-responsive img-rounded">
							{% endif %}
                            <div class="carousel-caption">
                                          <h2>{{ cat.title }}</h2>
                                      <p>{{cat.description}}</p>
                                   </div>
                                </div>
                            </div>
                        </div>


					  </div>
			</a>
            {% if request.user.is_superuser %}
                <a href="{% url 'snapdealapp:edit_category_html' cat.id %}" >edit</a>


	            <a href="{% url 'snapdealapp:delete_category_html' cat.id %}" >delete</a>
                {% endif %}
			</div>

	    {% endfor %}

		</div>
	</div>
	{% else %}
	    <p>No categories to show</p>
	{% endif %}
	</div>
{% endblock %}